name: CI

on:
  push:


jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Required with all actions
    - name: Validate HTML5
      uses: Cyb3r-Jak3/html5validator-action@v0.4.2
      id: validator
      with:
        root: ./
        css: true
    - uses: actions/upload-artifact@v2
      with:
        name: log
        path: log.log
    - name: Get information
      run: |
          echo "Result exit code: ${{ steps.validator.outputs.result }}"
